//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicsApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClinicsApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the resource is not a valid identifier.
        /// </summary>
        internal static string AnyValidator_InvalidId {
            get {
                return ResourceManager.GetString("AnyValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City of the clinic can only be {0}.
        /// </summary>
        internal static string CreateClinicRequestValidator_InvalidCity {
            get {
                return ResourceManager.GetString("CreateClinicRequestValidator_InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country for the clinic must be between {0} and {1}.
        /// </summary>
        internal static string CreateClinicRequestValidator_InvalidCountry {
            get {
                return ResourceManager.GetString("CreateClinicRequestValidator_InvalidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address of the clinic must be {0}.
        /// </summary>
        internal static string CreateClinicRequestValidator_InvalidStreet {
            get {
                return ResourceManager.GetString("CreateClinicRequestValidator_InvalidStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date must be before the To date.
        /// </summary>
        internal static string OfflineDoctorRequestValidator_FromAfterTo {
            get {
                return ResourceManager.GetString("OfflineDoctorRequestValidator_FromAfterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date must be a valid date and time.
        /// </summary>
        internal static string OfflineDoctorRequestValidator_InvalidFrom {
            get {
                return ResourceManager.GetString("OfflineDoctorRequestValidator_InvalidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date must be a valid date and time.
        /// </summary>
        internal static string OfflineDoctorRequestValidator_InvalidTo {
            get {
                return ResourceManager.GetString("OfflineDoctorRequestValidator_InvalidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date cannot be in the past.
        /// </summary>
        internal static string OfflineDoctorRequestValidator_PastFrom {
            get {
                return ResourceManager.GetString("OfflineDoctorRequestValidator_PastFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date cannot be in the past.
        /// </summary>
        internal static string OfflineDoctorRequestValidator_PastTo {
            get {
                return ResourceManager.GetString("OfflineDoctorRequestValidator_PastTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license certificate jurisdiction is not valid.
        /// </summary>
        internal static string RegisterClinicRequestValidator_InvalidJurisdiction {
            get {
                return ResourceManager.GetString("RegisterClinicRequestValidator_InvalidJurisdiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license certificate certificateNumber is invalid for this jurisdiction..
        /// </summary>
        internal static string RegisterClinicRequestValidator_InvalidNumber {
            get {
                return ResourceManager.GetString("RegisterClinicRequestValidator_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date must be before the To date.
        /// </summary>
        internal static string SearchAvailableDoctorsRequestValidator_FromAfterTo {
            get {
                return ResourceManager.GetString("SearchAvailableDoctorsRequestValidator_FromAfterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date must be a valid date and time.
        /// </summary>
        internal static string SearchAvailableDoctorsRequestValidator_InvalidFrom {
            get {
                return ResourceManager.GetString("SearchAvailableDoctorsRequestValidator_InvalidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date must be a valid date and time.
        /// </summary>
        internal static string SearchAvailableDoctorsRequestValidator_InvalidTo {
            get {
                return ResourceManager.GetString("SearchAvailableDoctorsRequestValidator_InvalidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date cannot be in the past.
        /// </summary>
        internal static string SearchAvailableDoctorsRequestValidator_PastFrom {
            get {
                return ResourceManager.GetString("SearchAvailableDoctorsRequestValidator_PastFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date cannot be in the past.
        /// </summary>
        internal static string SearchAvailableDoctorsRequestValidator_PastTo {
            get {
                return ResourceManager.GetString("SearchAvailableDoctorsRequestValidator_PastTo", resourceCulture);
            }
        }
    }
}
